/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pis;

import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import static pis.Datos.dosPalabras;
import static pis.OperacionesDeArchivos.buscarCedula;
import static pis.OperacionesDeArchivos.buscarNombre;
import static pis.OperacionesDeArchivos.buscarApellido;
import static pis.OperacionesDeArchivos.leerArchivo;
import static pis.OperacionesDeArchivos.eliminarDatos;
import static pis.Datos.isInt;
import static pis.OperacionesDeArchivos.leerRegistro;
/**
 *
 * @author PC-01
 */
public class Estudiante extends javax.swing.JFrame {
    /**
     * Creates new form Estudiante
     */
    public Estudiante() {
        super("KARATE UG");
        setIconImage(new ImageIcon(getClass().getResource("09.jpg")).getImage());
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("09.jpg")).getImage());
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        bEliminarAlumno.setVisible(false);
        tBusqueda.setText("ingrese "+criteriosCB.getSelectedItem().toString().toLowerCase());
        String[] dias={"1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31"};
        String[] mes={"Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre"};
        String[] anio={"1980","1981","1982","1983","1984","1985","1986","1987","1988","1989","1990","1991","1992","1993","1994","1995","1996","1997","1998","1999","2000","2001","2002","2003","2004","2005","2006","2007","2008","2009","2010","2011","2012","2013","2014","2015","2016","2017","2018","2019",};
        Dia.setModel(new javax.swing.DefaultComboBoxModel(dias));
        Dia.setSelectedIndex(0);
        Mes.setModel(new javax.swing.DefaultComboBoxModel(mes));
        Mes.setSelectedIndex(0);
        Anio.setModel(new javax.swing.DefaultComboBoxModel(anio));
        Anio.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tCedula = new javax.swing.JTextField();
        tNombre = new javax.swing.JTextField();
        tApellido = new javax.swing.JTextField();
        tTelefono = new javax.swing.JTextField();
        tDireccion = new javax.swing.JTextField();
        buscarB = new javax.swing.JButton();
        bAgregar = new javax.swing.JButton();
        bEliminarAlumno = new javax.swing.JButton();
        criteriosCB = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        tBusqueda = new javax.swing.JTextField();
        errorTel = new javax.swing.JLabel();
        errorCed = new javax.swing.JLabel();
        errorNom = new javax.swing.JLabel();
        bVerregistro = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Dia = new javax.swing.JComboBox<>();
        Mes = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Anio = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        Edad = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        errorApell = new javax.swing.JLabel();
        errorEd = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        registroTabla = new javax.swing.JTable();
        bsalir = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 51));

        jLabel1.setText("  Cédula:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Apellido:");

        jLabel4.setText("Télefono:");

        jLabel5.setText("Dirección:");

        tCedula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tCedulaMouseClicked(evt);
            }
        });
        tCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tCedulaActionPerformed(evt);
            }
        });

        tNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tNombreMouseClicked(evt);
            }
        });

        tApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tApellidoMouseClicked(evt);
            }
        });
        tApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tApellidoActionPerformed(evt);
            }
        });

        tTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tTelefonoMouseClicked(evt);
            }
        });
        tTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTelefonoActionPerformed(evt);
            }
        });

        buscarB.setText("Buscar");
        buscarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBActionPerformed(evt);
            }
        });

        bAgregar.setText("Agregar");
        bAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarActionPerformed(evt);
            }
        });

        bEliminarAlumno.setText("Eliminar estudiante");
        bEliminarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarAlumnoActionPerformed(evt);
            }
        });

        criteriosCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cédula", "Nombres", "Apellidos" }));
        criteriosCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criteriosCBActionPerformed(evt);
            }
        });

        jLabel6.setText("Criterio de búsqueda:");

        tBusqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tBusquedaMouseClicked(evt);
            }
        });
        tBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBusquedaActionPerformed(evt);
            }
        });

        errorTel.setText("*");

        errorCed.setText("*");

        errorNom.setText("*");

        bVerregistro.setText("Ver registro");
        bVerregistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVerregistroActionPerformed(evt);
            }
        });

        jLabel7.setText("Fecha De nacimiento:");

        Dia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", " " }));
        Dia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiaActionPerformed(evt);
            }
        });

        Mes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", " " }));

        jLabel8.setText("Dia:");

        jLabel9.setText("Mes:");

        jLabel10.setText("Año:");

        Anio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));

        jLabel11.setText("Edad:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel12.setText("ESTUDIANTE");

        errorApell.setText("*");

        errorEd.setText("*");

        registroTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        registroTabla.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(registroTabla);

        bsalir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bsalir.setText("REGRESAR");
        bsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsalirActionPerformed(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pis/logo.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buscarB, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(criteriosCB, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(errorNom, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(tApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(errorApell, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(errorEd))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(tTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(errorTel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Dia, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(14, 14, 14)
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Mes, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Anio, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(37, 37, 37)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(bEliminarAlumno)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(28, 28, 28)
                                                .addComponent(bAgregar))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(bsalir)
                                                .addComponent(bVerregistro, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(errorCed, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(226, 226, 226)
                                .addComponent(jLabel12)))))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(bEliminarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(bAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bVerregistro))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(errorCed, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(errorNom, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(tApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(errorApell, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(Dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(Mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(Anio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(errorEd)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(tTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(errorTel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buscarB, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(bsalir)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(criteriosCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBActionPerformed
        
        Datos estudiante=new Datos("","","","","","","","","",0);
        leerArchivo();
    switch(criteriosCB.getSelectedItem().toString()){
        case "Cédula":
        estudiante=buscarCedula(tBusqueda.getText());
        break;
        case "Nombres":
        estudiante=buscarNombre(tBusqueda.getText());
        break;
        case "Apellidos":
        estudiante=buscarApellido(tBusqueda.getText());
        break;
    }
    if(estudiante.getCedula().length()==0 && criteriosCB.getSelectedItem()=="Cédula"){
       JOptionPane.showMessageDialog(this,
        "No se encontró ningun alumno con esa cédula.", "Error",
        JOptionPane.ERROR_MESSAGE);
    }
    if(estudiante.getNombre().length()==0 && criteriosCB.getSelectedItem()=="Nombres"){
       JOptionPane.showMessageDialog(this,
        "No se encontró ningun alumno con esa nombre.", "Error",
        JOptionPane.ERROR_MESSAGE);
    }
    if(estudiante.getApellido().length()==0 && criteriosCB.getSelectedItem()=="Apellidos"){
       JOptionPane.showMessageDialog(this,
        "No se encontró ningun alumno con esa apellido.", "Error",
        JOptionPane.ERROR_MESSAGE);
    }
    if(estudiante.getCedula()!=""){
    bEliminarAlumno.setVisible(true);
    }
    tCedula.setText(estudiante.getCedula());
    tNombre.setText(estudiante.getNombre());
    tApellido.setText(estudiante.getApellido());
    Dia.setSelectedItem(estudiante.getDia());
    Mes.setSelectedItem(estudiante.getMes());
    Anio.setSelectedItem(estudiante.getAnio());
    Edad.setText(estudiante.getEdad());
    tTelefono.setText(estudiante.getTelefono());
    tDireccion.setText(estudiante.getDireccion());
    }//GEN-LAST:event_buscarBActionPerformed

    private void bAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarActionPerformed
        Datos estudiantes= new Datos(tCedula.getText(), tNombre.getText(), tApellido.getText(),Dia.getSelectedItem().toString(),Mes.getSelectedItem().toString(),Anio.getSelectedItem().toString(), Edad.getText(), tTelefono.getText(), tDireccion.getText(),0);
       boolean crear=true;
        if((tCedula.getText().length()!=0)&&(tNombre.getText().length()!=0)&&(tApellido.getText().length()!=0)&&(Edad.getText().length()!=0)&&(tTelefono.getText().length()!=0)&&(tDireccion.getText().length()!=0)&&(tDireccion.getText().length()!=0)){
       
       }else{
          crear=false;
             JOptionPane.showMessageDialog(this,
             "Debe llenar todos los campos.", "Error",
             JOptionPane.ERROR_MESSAGE);
       }
        if(tCedula.getText().length()==10 && isInt(tCedula.getText())){
            errorCed.setText(""); 
            tCedula.setForeground(Color.BLACK);
        }else{
           if(crear==true){
          crear=false;}
           tCedula.setForeground(Color.RED);
           errorCed.setText("*ingrese un número de cédula válido.");
        }
       if(isInt(tTelefono.getText())&& tTelefono.getText().length()<=10){
        errorTel.setText("");
           tTelefono.setForeground(Color.BLACK);
       }else{
           if(crear==true){
          crear=false;}
           tTelefono.setForeground(Color.RED);
           errorTel.setText("*ingrese solo dígitos.");
        }
       if(!(tNombre.getText().equals(""))){
       if(dosPalabras(tNombre.getText())){
           errorNom.setText("");
           tNombre.setForeground(Color.BLACK);
          
       }else{
           if(crear==true){
          crear=false;}
           tNombre.setForeground(Color.RED);
           errorNom.setText("*solo puede ingresar dos nombres.");
        }
       }
       if(!(tApellido.getText().equals(""))){
       if(dosPalabras(tApellido.getText())){
           errorApell.setText("");
           tApellido.setForeground(Color.BLACK);
       }else{
           if(crear==true){
          crear=false;}
           tApellido.setForeground(Color.RED);
           errorApell.setText("*solo puede ingresar dos apellidos.");
        }
       }
       if(isInt(Edad.getText())&& Edad.getText().length()<=2){
        errorEd.setText("");
           Edad.setForeground(Color.BLACK);
       }
       else{
           if(crear==true){
          crear=false;
           Edad.setForeground(Color.RED);
           errorEd.setText("*ingrese solo dígitos.");}
        }
       if(crear==true){
        try {
            tApellido.setForeground(Color.BLACK);
            OperacionesDeArchivos.agregarArchivo(estudiantes);
            JOptionPane.showMessageDialog(this,
                    "Se han agregado los datos del estudiante.", "Listo",
                    JOptionPane.INFORMATION_MESSAGE);
                 tCedula.setText("");
                 tNombre.setText("");
                 tApellido.setText("");
                 Edad.setText("");
                 tTelefono.setText("");
                 tDireccion.setText("");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this,
                    "No se han podido guardar los datos.", "Error",
                    JOptionPane.ERROR_MESSAGE);

        }
       }
       construirTabla(leerRegistro());
    }//GEN-LAST:event_bAgregarActionPerformed

    private void bEliminarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarAlumnoActionPerformed
     bEliminarAlumno.setVisible(false);
     Datos estudiante=new Datos("","","","","","","","","",0);
      leerArchivo();
    switch(criteriosCB.getSelectedItem().toString()){
        case "Cédula":
        estudiante=buscarCedula(tBusqueda.getText());
        break;
        case "Nombres":
        estudiante=buscarNombre(tBusqueda.getText());
        break;
        case "Apellidos":
        estudiante=buscarApellido(tBusqueda.getText());
        break;
    }
        try {
            eliminarDatos(estudiante);
                JOptionPane.showMessageDialog(this,
                    "Se han eliminado los datos del estudiante.", "Listo",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException ex) {
            Logger.getLogger(Estudiante.class.getName()).log(Level.SEVERE, null, ex);
        }
           tCedula.setText("");
           tNombre.setText("");
           tApellido.setText("");
           Edad.setText("");
           Dia.setSelectedIndex(0);
           Mes.setSelectedIndex(0);
           Anio.setSelectedIndex(0);
           tTelefono.setText("");
           tDireccion.setText("");
    }//GEN-LAST:event_bEliminarAlumnoActionPerformed

    private void criteriosCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criteriosCBActionPerformed
        tBusqueda.setText("ingrese "+criteriosCB.getSelectedItem().toString().toLowerCase());
    }//GEN-LAST:event_criteriosCBActionPerformed

    private void tBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBusquedaActionPerformed
      tBusqueda.setText("");
    }//GEN-LAST:event_tBusquedaActionPerformed

    private void tBusquedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tBusquedaMouseClicked
       tBusqueda.setText("");
    }//GEN-LAST:event_tBusquedaMouseClicked

    private void tCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tCedulaActionPerformed
        tCedula.setForeground(Color.BLACK);
    }//GEN-LAST:event_tCedulaActionPerformed

    private void tNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tNombreMouseClicked
         tNombre.setForeground(Color.BLACK);
    }//GEN-LAST:event_tNombreMouseClicked

    private void tApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tApellidoActionPerformed
         tApellido.setForeground(Color.BLACK);
    }//GEN-LAST:event_tApellidoActionPerformed

    private void tTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTelefonoActionPerformed
         tTelefono.setForeground(Color.BLACK);
    }//GEN-LAST:event_tTelefonoActionPerformed

    private void tCedulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tCedulaMouseClicked
        tCedula.setForeground(Color.BLACK);
    }//GEN-LAST:event_tCedulaMouseClicked

    private void tApellidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tApellidoMouseClicked
        tApellido.setForeground(Color.BLACK);
    }//GEN-LAST:event_tApellidoMouseClicked

    private void tTelefonoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tTelefonoMouseClicked
        tTelefono.setForeground(Color.BLACK);// TODO add your handling code here:
    }//GEN-LAST:event_tTelefonoMouseClicked

    private void bVerregistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVerregistroActionPerformed
   construirTabla(leerRegistro());
   
   
    }//GEN-LAST:event_bVerregistroActionPerformed
    public static void construirTabla(String[][] registro){
DefaultTableModel modelo = (DefaultTableModel)registroTabla.getModel();
modelo.setRowCount(registro.length);
modelo.setColumnCount(9);
JTableHeader head = registroTabla.getTableHeader();
TableColumnModel tcm = head.getColumnModel();
TableColumn tabCM = tcm.getColumn(0);
tabCM.setHeaderValue("Nombres");
TableColumn tabCM2 = tcm.getColumn(1);
tabCM2.setHeaderValue("Apellidos");
TableColumn tabCM3 = tcm.getColumn(2);
tabCM3.setHeaderValue("Cédula");
TableColumn tabCM4= tcm.getColumn(3);
tabCM4.setHeaderValue("Edad");
TableColumn tabCM5= tcm.getColumn(4);
tabCM5.setHeaderValue("Dia");
TableColumn tabCM6= tcm.getColumn(5);
tabCM6.setHeaderValue("Mes");
TableColumn tabCM7= tcm.getColumn(6);
tabCM7.setHeaderValue("Anio");
TableColumn tabCM8 = tcm.getColumn(7);
tabCM8.setHeaderValue("Télefono");
TableColumn tabCM9= tcm.getColumn(8);
tabCM9.setHeaderValue("Dirección");
for(int i=0;i<registro.length;i++){
for(int j=0;j<9;j++){
modelo.setValueAt(registro[i][j], i, j);
}
}
}
    private void DiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DiaActionPerformed

    private void bsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsalirActionPerformed
     Menu Ventana = new Menu();
   Ventana.setBounds(0,0,800,600);
   Ventana.setVisible(true);
    Ventana.setResizable(false);
      Ventana.setLocationRelativeTo(null);
       this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_bsalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Estudiante().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Anio;
    private javax.swing.JComboBox<String> Dia;
    private javax.swing.JTextField Edad;
    private javax.swing.JComboBox<String> Mes;
    private javax.swing.JButton bAgregar;
    private javax.swing.JButton bEliminarAlumno;
    private javax.swing.JButton bVerregistro;
    private javax.swing.JButton bsalir;
    private javax.swing.JButton buscarB;
    private javax.swing.JComboBox<String> criteriosCB;
    private javax.swing.JLabel errorApell;
    private javax.swing.JLabel errorCed;
    private javax.swing.JLabel errorEd;
    private javax.swing.JLabel errorNom;
    private javax.swing.JLabel errorTel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable registroTabla;
    private javax.swing.JTextField tApellido;
    private javax.swing.JTextField tBusqueda;
    private javax.swing.JTextField tCedula;
    private javax.swing.JTextField tDireccion;
    private javax.swing.JTextField tNombre;
    private javax.swing.JTextField tTelefono;
    // End of variables declaration//GEN-END:variables
}
