/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pis;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static pis.Archivo.QuestCinNegro;
import static pis.Archivo.QuestCinNegro1Dan;
import static pis.Archivo.QuestCinNegro2Dan;
import static pis.Archivo.QuestCinNegro3Dan;
import static pis.Archivo.actualizarArchivo;
import static pis.Archivo.llenarLista;
import static pis.Archivo.preguntas;


public class PreguntasVentana extends javax.swing.JFrame {

    /**
     * Creates new form QuestionarioVentana
     */
    public PreguntasVentana() throws IOException {
        super("Preguntas");
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        llenarLista();
        mostrarTCN();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tPreguntas = new javax.swing.JTextArea();
        comboNiveles = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        header = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        numPreguntas = new javax.swing.JComboBox<>();
        textPregunta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tPreguntas.setEditable(false);
        tPreguntas.setColumns(20);
        tPreguntas.setRows(5);
        jScrollPane1.setViewportView(tPreguntas);

        comboNiveles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Cinturón negro","Cinturón negro 1er Dan","Cinturón negro 2do Dan","Cinturón negro 3er Dan"}));
        comboNiveles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboNivelesMouseClicked(evt);
            }
        });
        comboNiveles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboNivelesActionPerformed(evt);
            }
        });

        jLabel1.setText("Nivel del temario :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Temario específico general");

        header.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel3.setText("Seleccione el número de pregunta que desea editar:");

        numPreguntas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", ""}));
        numPreguntas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numPreguntasActionPerformed(evt);
            }
        });

        textPregunta.setEditable(false);
        textPregunta.setText("    ");

        jLabel4.setText("Pregunta:");

        jButton2.setText("Editar Pregunta");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Guardar cambios");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Regresar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(266, 266, 266)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(209, 209, 209)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboNiveles, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numPreguntas, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboNiveles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(numPreguntas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboNivelesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboNivelesMouseClicked

    }//GEN-LAST:event_comboNivelesMouseClicked

    private void comboNivelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboNivelesActionPerformed
       switch(comboNiveles.getSelectedItem().toString()){
    case"Cinturón negro":mostrarTCN();
    header.setText("                                       Temario Específico General Cinturón Negro");break;
    case"Cinturón negro 1er Dan":mostrarTCN1D();
    header.setText("                            Temario Específico General Cinturón Negro Primer Dan");break;
    case"Cinturón negro 2do Dan":mostrarTCN2D();
    header.setText("                            Temario Específico General Cinturón Negro Segundo Dan");break;
    case"Cinturón negro 3er Dan":mostrarTCN3D();
    header.setText("                            Temario Específico General Cinturón Negro Tercer Dan");break;
    }
    }//GEN-LAST:event_comboNivelesActionPerformed

    private void numPreguntasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numPreguntasActionPerformed
         switch(comboNiveles.getSelectedItem().toString()){
    case"Cinturón negro":selecPreguntaN1();break;
    case"Cinturón negro 1er Dan":selecPreguntaN2();break;
    case"Cinturón negro 2do Dan":selecPreguntaN3();;break;
    case"Cinturón negro 3er Dan":selecPreguntaN4();break;
    }   
    }//GEN-LAST:event_numPreguntasActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
       if(textPregunta.getText().length()!=0){
        switch(comboNiveles.getSelectedItem().toString()){
        case"Cinturón negro":changePreguntaN1();break;
        case"Cinturón negro 1er Dan":changePreguntaN2();break;
        case"Cinturón negro 2do Dan":changePreguntaN3();;break;
        case"Cinturón negro 3er Dan":changePreguntaN4();break;
    }
        deshabilitarCampos();
            actualizarArchivo(); }
       else{
            JOptionPane.showMessageDialog(this,
        "Debe llenar el campo.", "Error",
        JOptionPane.ERROR_MESSAGE);
       }// TODO add your handling code here:
        } catch (IOException ex) {
            Logger.getLogger(PreguntasVentana.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     habilitarCampos();   // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      Menu Ventana = new Menu();
   Ventana.setBounds(0,0,800,600);
   Ventana.setVisible(true);
    Ventana.setResizable(false);
      Ventana.setLocationRelativeTo(null);
       this.setVisible(false);   
    }//GEN-LAST:event_jButton4ActionPerformed
    private void selecPreguntaN1(){
    for(Preguntas q:QuestCinNegro){
    if(q.getNumero()==(numPreguntas.getSelectedIndex()+1)){
    textPregunta.setText(q.getQuestion());
    }
    }
    }
    private void changePreguntaN1(){
    for(Preguntas q:QuestCinNegro){
    if(q.getNumero()==(numPreguntas.getSelectedIndex()+1)){
    q.setQuestion(textPregunta.getText());
    }
    }
    }
    private void selecPreguntaN2(){
    for(Preguntas q:QuestCinNegro1Dan){
    if(q.getNumero()==(numPreguntas.getSelectedIndex()+1)){
    textPregunta.setText(q.getQuestion());
    }
    }
    }
     private void changePreguntaN2(){
    for(Preguntas q:QuestCinNegro1Dan){
    if(q.getNumero()==(numPreguntas.getSelectedIndex()+1)){
    q.setQuestion(textPregunta.getText());
    }
    }
    }
    private void selecPreguntaN3(){
    for(Preguntas q:QuestCinNegro2Dan){
    if(q.getNumero()==(numPreguntas.getSelectedIndex()+1)){
    textPregunta.setText(q.getQuestion());
    }
    }
    }
    private void changePreguntaN3(){
    for(Preguntas q:QuestCinNegro2Dan){
    if(q.getNumero()==(numPreguntas.getSelectedIndex()+1)){
    q.setQuestion(textPregunta.getText());
    }
    }
    }
    private void selecPreguntaN4(){
    for(Preguntas q:QuestCinNegro3Dan){
    if(q.getNumero()==(numPreguntas.getSelectedIndex()+1)){
    textPregunta.setText(q.getQuestion());
    }
    }
    }
    private void changePreguntaN4(){
    for(Preguntas q:QuestCinNegro3Dan){
    if(q.getNumero()==(numPreguntas.getSelectedIndex()+1)){
     q.setQuestion(textPregunta.getText());
    }
    }
    }
    private void habilitarCampos(){
    textPregunta.setEditable(true);
 
    }
    private void deshabilitarCampos(){
    textPregunta.setEditable(false);
  
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PreguntasVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PreguntasVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PreguntasVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PreguntasVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new PreguntasVentana().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(PreguntasVentana.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
   private void mostrarTCN(){ 
    tPreguntas.setText("");   
   numPreguntas.removeAllItems();
   for(Preguntas p:QuestCinNegro){
   numPreguntas.addItem(Integer.toString(p.getNumero()));
   tPreguntas.setText(tPreguntas.getText()+"\n"+p.getNumero()+".-"+p.getQuestion()+"\n");
   }
    }
   private void mostrarTCN1D(){
   tPreguntas.setText("");
   numPreguntas.removeAllItems();
    for(Preguntas p:QuestCinNegro1Dan){
   numPreguntas.addItem(Integer.toString(p.getNumero()));
   tPreguntas.setText(tPreguntas.getText()+"\n"+p.getNumero()+".-"+p.getQuestion()+"\n");
   }
    }
   private void mostrarTCN2D(){
    tPreguntas.setText("");
    numPreguntas.removeAllItems();
   for(Preguntas p:QuestCinNegro2Dan){
   numPreguntas.addItem(Integer.toString(p.getNumero()));
   tPreguntas.setText(tPreguntas.getText()+"\n"+p.getNumero()+".-"+p.getQuestion()+"\n");
   }
    }
  private void mostrarTCN3D(){
   tPreguntas.setText("");
   numPreguntas.removeAllItems();
  for(Preguntas p:QuestCinNegro3Dan){
    numPreguntas.addItem(Integer.toString(p.getNumero()));
   tPreguntas.setText(tPreguntas.getText()+"\n"+p.getNumero()+".-"+p.getQuestion()+"\n");
   }
    }  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboNiveles;
    private javax.swing.JLabel header;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> numPreguntas;
    private javax.swing.JTextArea tPreguntas;
    private javax.swing.JTextField textPregunta;
    // End of variables declaration//GEN-END:variables
}
