/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pis;

import static pis.OperacionesArchivos.buscarCedula;
import java.io.IOException;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import static pis.Datos.dosPalabras;
import static pis.Datos.isInt;
/**
 *
 * @author Green Studio
 */
public class VentanaInstructor extends javax.swing.JFrame {
 Instructor ins;
    /**
     * Creates new form VentanaInstructor
     */
    public VentanaInstructor() {
        super("Instructor");
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("09.jpg")).getImage());
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        String[] cinturon = {"Cinturon Negro","Cinturon Negro Primer Dan","Cinturon Negro Segundo Dan","Cinturon Negro Tercer Dan","Cinturon Negro Cuarto Dan","Cinturon Negro Quinto Dan","Altos Grados sexto Dan y Sucecivos"};
        tCinturon.setModel(new javax.swing.DefaultComboBoxModel(cinturon));
        tCinturon.setSelectedIndex(0);
        construirTabla(OperacionesArchivos.leerRegistro());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tCedula = new javax.swing.JTextField();
        tNombre = new javax.swing.JTextField();
        tApellido = new javax.swing.JTextField();
        tEdad = new javax.swing.JTextField();
        tTelefono = new javax.swing.JTextField();
        tCinturon = new javax.swing.JComboBox<>();
        bCrear = new javax.swing.JButton();
        bBuscar = new javax.swing.JButton();
        tBuscar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        bLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tTabla = new javax.swing.JTable();
        bsalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pis/logo.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("INSTRUCTOR");

        jLabel3.setText("Cédula : ");

        jLabel4.setText("Nombre : ");

        jLabel5.setText("Apellido:");

        jLabel6.setText("Cinturon:");

        jLabel7.setText("Edad:");

        jLabel8.setText("Telèfono:");

        tNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNombreActionPerformed(evt);
            }
        });

        tEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tEdadActionPerformed(evt);
            }
        });

        tCinturon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        tCinturon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tCinturonActionPerformed(evt);
            }
        });

        bCrear.setText("AGREGAR");
        bCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrearActionPerformed(evt);
            }
        });

        bBuscar.setText("BUSCAR");
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });

        jLabel9.setText("Ingrese una cedula:");

        bLimpiar.setText("LIMPIAR");
        bLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimpiarActionPerformed(evt);
            }
        });

        tTabla.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cedula", "Nombres", "Apellidos", "Edad", "Cinturon"
            }
        ));
        tTabla.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tTabla);
        tTabla.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        bsalir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bsalir.setText("REGRESAR");
        bsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(tCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tCinturon, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(tEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(bBuscar)
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addComponent(tBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(bCrear)
                                .addComponent(bLimpiar))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(bsalir)
                                .addGap(153, 153, 153))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(tCinturon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(bCrear)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bBuscar)
                            .addComponent(tBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(bLimpiar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(tTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bsalir))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNombreActionPerformed

    private void tEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tEdadActionPerformed

    private void tCinturonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tCinturonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tCinturonActionPerformed

    private void bCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCrearActionPerformed
        Instructor instruc= new Instructor(tCedula.getText(), tNombre.getText(), tApellido.getText(),tEdad.getText(),tCinturon.getSelectedItem().toString(), tTelefono.getText());
       boolean archivo=true;
        if((tCedula.getText().length()!=0)&&(tNombre.getText().length()!=0)&&(tApellido.getText().length()!=0)&&(tEdad.getText().length()!=0)&&(tTelefono.getText().length()!=0)){
       
       }else{
          archivo=false;
             JOptionPane.showMessageDialog(this,
             "Debe llenar todos los campos.", "Error",
             JOptionPane.ERROR_MESSAGE);
       }if(tCedula.getText().length()!=0){
           if(tCedula.getText().length()==10 && isInt(tCedula.getText())){
        }else{
           if(archivo==true){
          archivo=false;}
               JOptionPane.showMessageDialog(this,
             "Ingrese una Cedula valida.", "Error",
             JOptionPane.ERROR_MESSAGE); 
        }
       }else{}
       if(isInt(tTelefono.getText())&& tTelefono.getText().length()<=10){
       
       }else{
           if(archivo==true){
          archivo=false;}
              JOptionPane.showMessageDialog(this,
             "Ingrese solo numeros", "Error",
             JOptionPane.ERROR_MESSAGE);
        }
       if(dosPalabras(tNombre.getText())){         
       }else{
           if(archivo==true){
          archivo=false;}
            JOptionPane.showMessageDialog(this,
             "Ingrese solo dos nombres", "Error",
             JOptionPane.ERROR_MESSAGE);
        }
       if(dosPalabras(tApellido.getText())){
       }else{
           if(archivo==true){
          archivo=false;}
              JOptionPane.showMessageDialog(this,
             "Ingrese dos apellidos.", "Error",
             JOptionPane.ERROR_MESSAGE);
        }
       if(isInt(tEdad.getText())&& tEdad.getText().length()<=2){
   
       }
       else{
           if(archivo==true){
          archivo=false;
            JOptionPane.showMessageDialog(this,
             "Ingrese una edad valida", "Error",
             JOptionPane.ERROR_MESSAGE);
        }}
       if(archivo==true){
           OperacionesArchivos.crearArchivo(instruc);
           JOptionPane.showMessageDialog(this,
                   "Se han agregado los datos del estudiante.", "Listo",
                   JOptionPane.INFORMATION_MESSAGE);
           tCedula.setText("");
           tNombre.setText("");
           tApellido.setText("");
           tEdad.setText("");
           tTelefono.setText("");  
       construirTabla(OperacionesArchivos.leerRegistro());
       }
             
    }//GEN-LAST:event_bCrearActionPerformed
 
    
    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarActionPerformed
            Instructor instruc =new Instructor("","","","","","");
        OperacionesArchivos.leerArchivoI();
        instruc = buscarCedula(tBuscar.getText());
        if(instruc.getCedula().length()==0 ){
        JOptionPane.showMessageDialog(this,
        "No se encontró ningun dato.", "Error",
        JOptionPane.ERROR_MESSAGE);
        }
   
    tCedula.setText(instruc.getCedula());
    tNombre.setText(instruc.getNombre());
    tApellido.setText(instruc.getApellido());
    tCinturon.setSelectedItem(instruc.getCinturon());
    tEdad.setText(instruc.getEdad());
    tTelefono.setText(instruc.getTelefono());
 // TODO add your handling code here:
    }//GEN-LAST:event_bBuscarActionPerformed

    private void bLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimpiarActionPerformed
        tCedula.setText("");
        tNombre.setText("");
        tApellido.setText("");
        tEdad.setText("");
        tCinturon.setSelectedIndex(0);
        tTelefono.setText("");
        tBuscar.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_bLimpiarActionPerformed

    private void bsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsalirActionPerformed
        Menu Ventana = new Menu();
        Ventana.setBounds(0,0,800,600);
        Ventana.setVisible(true);
        Ventana.setResizable(false);
        Ventana.setLocationRelativeTo(null);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_bsalirActionPerformed
       public static void construirTabla(String[][] registro){
DefaultTableModel modelo = (DefaultTableModel)tTabla.getModel();
modelo.setRowCount(registro.length);
modelo.setColumnCount(6);
JTableHeader head = tTabla.getTableHeader();
TableColumnModel tcm = head.getColumnModel();
TableColumn tabCM = tcm.getColumn(0);
tabCM.setHeaderValue("Cèdula");
TableColumn tabCM2 = tcm.getColumn(1);
tabCM2.setHeaderValue("Nombre");
TableColumn tabCM3 = tcm.getColumn(2);
tabCM3.setHeaderValue("Apellido");
TableColumn tabCM4= tcm.getColumn(3);
tabCM4.setHeaderValue("Edad");
TableColumn tabCM5= tcm.getColumn(4);
tabCM5.setHeaderValue("Cinturòn");
TableColumn tabCM6= tcm.getColumn(5);
tabCM6.setHeaderValue("Telèfono");
for(int i=0;i<registro.length;i++){
for(int j=0;j<6;j++){
modelo.setValueAt(registro[i][j], i, j);
}
}
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInstructor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInstructor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInstructor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInstructor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInstructor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton bCrear;
    private javax.swing.JButton bLimpiar;
    private javax.swing.JButton bsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tApellido;
    private javax.swing.JTextField tBuscar;
    private javax.swing.JTextField tCedula;
    private javax.swing.JComboBox<String> tCinturon;
    private javax.swing.JTextField tEdad;
    private javax.swing.JTextField tNombre;
    private static javax.swing.JTable tTabla;
    private javax.swing.JTextField tTelefono;
    // End of variables declaration//GEN-END:variables
}
